
package it.gestpay.wscryptdecrypt.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCryptDecrypt", targetNamespace = "https://ecomm.sella.it/", wsdlLocation = "https://testecomm.sella.it/gestpay/GestPayWS/WsCryptDecrypt.asmx?wsdl")
public class WSCryptDecrypt
    extends Service
{

    private final static URL WSCRYPTDECRYPT_WSDL_LOCATION;
    private final static WebServiceException WSCRYPTDECRYPT_EXCEPTION;
    private final static QName WSCRYPTDECRYPT_QNAME = new QName("https://ecomm.sella.it/", "WSCryptDecrypt");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://testecomm.sella.it/gestpay/GestPayWS/WsCryptDecrypt.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCRYPTDECRYPT_WSDL_LOCATION = url;
        WSCRYPTDECRYPT_EXCEPTION = e;
    }

    public WSCryptDecrypt() {
        super(__getWsdlLocation(), WSCRYPTDECRYPT_QNAME);
    }

    public WSCryptDecrypt(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCRYPTDECRYPT_QNAME, features);
    }

    public WSCryptDecrypt(URL wsdlLocation) {
        super(wsdlLocation, WSCRYPTDECRYPT_QNAME);
    }

    public WSCryptDecrypt(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCRYPTDECRYPT_QNAME, features);
    }

    public WSCryptDecrypt(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCryptDecrypt(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCryptDecryptSoap
     */
    @WebEndpoint(name = "WSCryptDecryptSoap")
    public WSCryptDecryptSoap getWSCryptDecryptSoap() {
        return super.getPort(new QName("https://ecomm.sella.it/", "WSCryptDecryptSoap"), WSCryptDecryptSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCryptDecryptSoap
     */
    @WebEndpoint(name = "WSCryptDecryptSoap")
    public WSCryptDecryptSoap getWSCryptDecryptSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://ecomm.sella.it/", "WSCryptDecryptSoap"), WSCryptDecryptSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCRYPTDECRYPT_EXCEPTION!= null) {
            throw WSCRYPTDECRYPT_EXCEPTION;
        }
        return WSCRYPTDECRYPT_WSDL_LOCATION;
    }

}
