package it.gestpay.wscryptdecrypt.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Wed Mar 15 16:31:23 CET 2017
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "https://ecomm.sella.it/", name = "WSCryptDecryptSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WSCryptDecryptSoap {

    @WebMethod(operationName = "Decrypt", action = "https://ecomm.sella.it/Decrypt")
    @RequestWrapper(localName = "Decrypt", targetNamespace = "https://ecomm.sella.it/", className = "it.gestpay.wscryptdecrypt.model.Decrypt")
    @ResponseWrapper(localName = "DecryptResponse", targetNamespace = "https://ecomm.sella.it/", className = "it.gestpay.wscryptdecrypt.model.DecryptResponse")
    @WebResult(name = "DecryptResult", targetNamespace = "https://ecomm.sella.it/")
    public it.gestpay.wscryptdecrypt.model.DecryptResponse.DecryptResult decrypt(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String shopLogin,
        @WebParam(name = "CryptedString", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String cryptedString
    );

    @WebMethod(operationName = "Encrypt", action = "https://ecomm.sella.it/Encrypt")
    @RequestWrapper(localName = "Encrypt", targetNamespace = "https://ecomm.sella.it/", className = "it.gestpay.wscryptdecrypt.model.Encrypt")
    @ResponseWrapper(localName = "EncryptResponse", targetNamespace = "https://ecomm.sella.it/", className = "it.gestpay.wscryptdecrypt.model.EncryptResponse")
    @WebResult(name = "EncryptResult", targetNamespace = "https://ecomm.sella.it/")
    public it.gestpay.wscryptdecrypt.model.EncryptResponse.EncryptResult encrypt(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String shopLogin,
        @WebParam(name = "uicCode", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String uicCode,
        @WebParam(name = "amount", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String amount,
        @WebParam(name = "shopTransactionId", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String shopTransactionId,
        @WebParam(name = "cardNumber", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String cardNumber,
        @WebParam(name = "expiryMonth", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String expiryMonth,
        @WebParam(name = "expiryYear", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String expiryYear,
        @WebParam(name = "buyerName", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String buyerName,
        @WebParam(name = "buyerEmail", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String buyerEmail,
        @WebParam(name = "languageId", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String languageId,
        @WebParam(name = "cvv", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String cvv,
        @WebParam(name = "customInfo", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String customInfo,
        @WebParam(name = "requestToken", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String requestToken,
        @WebParam(name = "ppSellerProtection", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String ppSellerProtection,
        @WebParam(name = "shippingDetails", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.ShippingDetails shippingDetails,
        @WebParam(name = "paymentTypes", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.PaymentTypes paymentTypes,
        @WebParam(name = "paymentTypeDetail", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.PaymentTypeDetail paymentTypeDetail,
        @WebParam(name = "redFraudPrevention", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String redFraudPrevention,
        @WebParam(name = "Red_CustomerInfo", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.RedCustomerInfo redCustomerInfo,
        @WebParam(name = "Red_ShippingInfo", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.RedShippingInfo redShippingInfo,
        @WebParam(name = "Red_BillingInfo", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.RedBillingInfo redBillingInfo,
        @WebParam(name = "Red_CustomerData", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.RedCustomerData redCustomerData,
        @WebParam(name = "Red_CustomInfo", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.RedCustomInfo redCustomInfo,
        @WebParam(name = "Red_Items", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.RedItems redItems,
        @WebParam(name = "Consel_MerchantPro", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String conselMerchantPro,
        @WebParam(name = "Consel_CustomerInfo", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.ConselCustomerInfo conselCustomerInfo,
        @WebParam(name = "payPalBillingAgreementDescription", targetNamespace = "https://ecomm.sella.it/")
        java.lang.String payPalBillingAgreementDescription,
        @WebParam(name = "OrderDetails", targetNamespace = "https://ecomm.sella.it/")
        it.gestpay.wscryptdecrypt.model.EcommGestpayPaymentDetails orderDetails
    );
}
